### ISSUE TITLE
Consider using conda to install and manage Python deps instead of pip

### ISSUE THREAD

**Issue by davidrpugh** [manifoldai/orbyter-docker#1]
@abng88 Awesome project! Have you considered using the Anaconda Python distribution (specifically [miniconda](https://conda.io/miniconda.html)) to install and mange Python dependencies instead of installing Python using 'apt-get' and managing dependencies using pip.  Using conda is the approach taken by Jupyter in their [Dockerfiles](https://github.com/jupyter/docker-stacks).

IMHO Python data science community seems to have standardized on Anaconda distribution and conda as the package management tool of choice.

**Comment by resdntalien** [comment]
@davidrpugh Sorry so late in cleaning this up -- but that is a good idea, but a major change for this lineage. For now, we're gonna stick with the apt-get python installation for Ubuntu and pip for the package management. If you want, you can make a separate set of images in Orbyter that uses conda though -- they can certainly live side by side. There shouldn't be any problem with that. If someone want to use the conda version, they just point he cookiecutter to that image instead.
