### ISSUE TITLE
Get TQDM to work in JupyterLab (and other JupyterLab extensions)

### ISSUE THREAD

**Issue by resdntalien** [manifoldai/orbyter-docker#60]
We need node.js and npm in the image so we can install JupyterLab extensions.

**Comment by resdntalien** [comment]
RUN apt update
RUN apt -y install nodejs
RUN apt -y install npm
RUN jupyter nbextension enable --py widgetsnbextension
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager

**Comment by resdntalien** [comment]
This allows TQDM to be run inside Jupyter Lab notebooks. Without this extension it doesn't work. It is unclear what the best way to get this into the Orbyter docker build.

**Comment by mstefferson** [comment]
Why are doing this? Are you looking to move everything to Jupyter-lab. I don't actually think this is worth doing. Most people don't use Jupyter lab, and there is a cost to having huge images and supporting more dependencies.

**Comment by mstefferson** [comment]
If a project wants to use Jupyter lab, they should just install in that project repo.

**Comment by resdntalien** [comment]
We have cut over since Orbyter 3.0 to JupyterLab as our default Jupyter server.  The is encoded in the docker-compose.yml. There are a number of benefits in the development environment as compared to Jupyter Notebooks.  As far as I understand, Jupyter notebooks are going to be sunsetted at some point in the future (many years away still) and that dev effort has already moved to JuypterLab.  

Though we have cut over to JupyterLab, in order to install the extensions you need npm installed in the image. It is fairly lightweight in terms of space. The issue is the time. The dockerfile with the jupyterlab extensions takes 10mins to build. It makes sense to push it upstream because we have standardized on JupyterLab as our dev environment.

**Comment by resdntalien** [comment]
Fixed by #61
